### ISSUE TITLE
[Bug Report]: Can't change resource packs.

### ISSUE THREAD

**Issue by deathbytophats** [TeamAOF/Craftoria#186]
### Modpack Version

21.1.66

### Describe your issue.

I am trying to put my preferred resource pack at the top of the list but everytime it gets sorted to the bottom. Even when I deleted every resource pack except the one I want all the other ones I deleted are still activated. I've tried restarting after every new change or idea nothing is letting me alter the load order in any way.

### Have you modified the modpack?

Yes

### User Modifications

Added resource packs

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Aetherlight** [comment]
the issue is Paxi. Delete the resources from the paxi config folder. 

"Usually, data packs have to be loaded separately for every world. Paxi adds the paxi folder in your Minecraft config folder, where you can place data and resource packs that will automatically be loaded for every world. The first time you run Paxi, the paxi folder will be created in your Minecraft config directory."

https://www.curseforge.com/minecraft/mc-mods/paxi-neoforge
