### ISSUE TITLE
AE2 Guide

### ISSUE THREAD

**Issue by Damalas75** [TeamAOF/Craftoria#192]
### Describe your suggestion

The item Guide from AE2 appears multiple times in modpack, every meteorite you break gives you 1 and the quest line also gives you one as well, and is not needed in the quest if it already in the drop of the Meteorite. 

### Why would you like this added/changed?

To aid in dealing with Modded Inventory management as it not required to have multiple Guide from the AE2.

**Comment by SubordinalBlue** [comment]
Why would you break multiple meteorites?

AE2's intention is to farm more budding certus after finding enough material from just one.

Also... just throw away the extra copies?

It's in the quest so one could have that information before finding a Meteorite.

**Comment by bbarry** [comment]
Eh... meteorites are a little too common IMO and it is kinda useful to break 4 of them to collect 4 of each inscriber and 4 flawless to put around a crystal growth accel and harvest with a JDT advanced machine.

Still I'd rather have a bunch of guides than none, they are easy to trash. Having too many mod guide books is a not-problem.

Honestly I wish every mod had a standard guide book generation process like either of these:

* anvil - book + any item from mod
* lectern - sneak click on lectern while holding any item in right hand and book drops from mod that adds that item if it exists

Also every guide book should have a standard unique tag `#guide:{mod_id}` to facilitate such a recipe and make it easy to search JEI for guides (add-on mods could extend the tag of a guide relevant to them so that the standard recipe worked to get the guide for a common set of mods such as the worn notebook for ars stuff).

**Comment by SubordinalBlue** [comment]
Discussion noted; closing issue. Cheers.
