### ISSUE TITLE
[Bug Report]: Electric Blast furnace resets efficiency when using Temporal Pouch on any machine

### ISSUE THREAD

**Issue by ThomasHK2003** [TeamAOF/Craftoria#288]
### Modpack Version

1.7.2 ?

### Describe your issue.

whenever i use the temporal pouch to speed up other machines, it resets the efficiency counter on the electric blast furnace. It makes somewhat sense that it doesnt work on that spesific machine, but not beeing able to speed up other processes without ruining the efficienct of my aluminium production blows :/

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kazuhiko-Gushiken** [comment]
@ThomasHK2003 My guess (because this has happened to me in the past) is that you speed it up a little too much that it uses all the power in it's buffer and thus stopping the machine and killing the efficiency. Do a test with only a 2x on a recipe that doesn't use too much power. Watch the internal energy buffer. Go up to 4x, watch it until it plummets and kills efficiency.

**Comment by Kazuhiko-Gushiken** [comment]
gonna close this, reopen if needed
